# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ github_actions ]
  pull_request:
    branches: [ github_actions ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  stackstorm-ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    services:
      mongodb:
        image: mongo:4.0-xenial
      rabbitmq:
        image: rabbitmq:3.6

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: "Unit Tests, Pack Tests (Python 3.6)"
        run: |
          ./scripts/travis/install-requirements.sh
          sed -r "s/stanley/travis/" <conf/st2.dev.conf >"${ST2_CONF}"
          sudo scripts/travis/add-itest-user-key.sh
          sudo .circle/add-itest-user.sh
          if [[ "${TASK}" = *'-packs-tests'* ]] || [[ "${TASK}" = *'-integration'* ]]; then sudo scripts/travis/permissions-workaround.sh; fi
        env:
          ENABLE_COVERAGE: no
          IS_NIGHTLY_BUILD: no
          COLUMNS: 120
          PYLINT_CONCURRENCY: 2
          ST2_CONF: "conf/st2.travis.conf"
          NOSE_TIME: no
          TASK: "compilepy3 ci-py3-unit ci-py3-packs-tests"
          CACHE_NAME: "py3"
          PYTHON_VERSION: "python3.6"
          COMMAND_THRESHOLD: 750
